config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'static_pages#home'

  resources :campaigns do
    get  :preview, on: :member, as: :preview_campaign
    post  :send, on: :member, to: 'campaigns#send_templated_email', as: :send_campaign
    resources :contacts do
      get :upload, on: :collection
      post :import, on: :collection
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_campaigns.html.erb
<h2> List of Your Past Campaigns </h2>
<ul>
<% current_user.campaigns.each do |campaign| %>
<li><strong>Campaign:</strong> <%= link_to campaign.name, campaign_path(campaign.id) %>. <strong>Contacts</strong> <%= campaign.contacts.count %></li>
<% end %>
</ul>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
<h1>Welcome! Let's make an impact today</h1>
<h2>Let's create a campaign:</h2>
  <%= link_to('Create a Campaign', new_campaign_path) %>
  <%= render('campaigns') %>
  <%= link_to('Log Out', destroy_user_session_path, :method => :delete)  %>
<% else %>
<h1>Reach out to 100 people via your Gmail account</h1>
  <%= link_to('Log in via your Google Account', user_google_oauth2_omniauth_authorize_url) %>
<% end %>