config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'static_pages#home'

  resources :campaigns do
    get  :preview, on: :member, as: :preview_campaign
    post  :send, on: :member, to: 'campaigns#send_templated_email', as: :send_campaign
    resources :contacts do
      get :upload, on: :collection
      post :import, on: :collection
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Sidekiq::Web => '/sidekiq'
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :user
  has_many :contacts, dependent: :destroy
  accepts_nested_attributes_for :contacts
  validates :name, presence: true
  validates :email, presence: true

  enum status: { draft: 0, sent: 1 }

  def render(contact)
    email.gsub(/{{[\w]+}}/) {|var| contact.contact_attributes.find_by(attribute_name: var.scan(/[^({{|}})]/).join).attribute_value }
  end

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_campaign, only: [:show, :edit, :update, :destroy, :send_templated_email, :import]
  before_action :show_progress_bar
  helper_method :render_email


  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = current_user.campaigns
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
    if @campaign.user_id != current_user.id
      redirect_to campaigns_url
      flash[:notice] = 'A typo in the URL! Check out your campaigns below'
    end
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = current_user.campaigns.new(campaign_params)

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to upload_campaign_contacts_path(@campaign), notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1
  # PATCH/PUT /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { render :edit; flash[:notice] = 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def preview
    @campaign = Campaign.find_by_id(params[:id])
  end

  def send_templated_email
      token = Token.find_by_email(@campaign.user.email)
      token.update_token!
      @campaign.contacts.each do |contact|
        EmailJob.perform_later(
                        sender:   @campaign.user.email,
                        subject:  @campaign.name,
                        email:    contact.email,
                        body:     @campaign.render(contact),
                        token:    token.refresh_token
                        )
      end
      @campaign.sent!
      redirect_to(root_url, notice: "We just sent #{@campaign.contacts.count} emails via your Gmail account.")
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_params
      params.require(:campaign).permit(:name, :email)
    end

    def show_progress_bar
      @show_progress_bar = true
    end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper


  
end

app/views/campaigns/_campaign_variables.html.erb
<h3>Merge Tags</h3>
 <ol>
<% campaign.contacts.first.contact_attributes.all.each do |attribute| %>

  <li>{{<%= attribute.attribute_name %>}}</li>

<% end %>
 </ol>

app/views/campaigns/_form.html.erb
<%= form_for(campaign) do |f| %>
  <% if campaign.errors.any? %>
    <% campaign.errors.full_messages.each do |message| %>
      <%= js add_gritter(message, title: "Errors", sticky: false) %>
    <% end %>
  <% end %>

  <div class="field form-group">
    <%= f.label "Subject" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label "The body of your email" %>
    <%= f.text_area :email, class: "form-control", rows: "10" %>
  </div>


  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<div class="row">
  <div class="col-md-4">
    <%= render 'campaign_variables', campaign: @campaign %>
  </div>
  <div class="col-md-8">
    <%= render 'form', campaign: @campaign %>
  </div>
</div>
<% @campaign.errors.each do |error| %>
  <ul>
    <li><%= error%></li>
  </ul>
<% end %>



<%= link_to 'Preview This Campaign', preview_campaign_campaign_path(@campaign) %>

app/views/campaigns/index.html.erb
<p id="notice"><%= notice %></p>

<h2 id="DraftCampaigns">Draft Campaigns</h2>
<% if(@campaigns.draft.count > 0) %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campaigns.draft.each do |campaign| %>
      <tr>
        <td><%= campaign.name %></td>
        <td><%= link_to 'Show', campaign %></td>
        <td><%= link_to 'Edit', edit_campaign_path(campaign) %></td>
        <td><%= link_to 'Destroy', campaign, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>

<p>You don't have any draft campaigns at the moment.</p>
<% end %>

<h2 id="SentCampaigns">Sent Campaigns</h2>
<% if(@campaigns.sent.count > 0) %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campaigns.sent.each do |campaign| %>
      <tr>
        <td><%= campaign.name %></td>
        <td><%= link_to 'Show', campaign %></td>
        <td><%= link_to 'Edit', edit_campaign_path(campaign) %></td>
        <td><%= link_to 'Destroy', campaign, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>

<p>You don't have any sent campaigns at the moment.</p>
<% end %>
<br>

<%= link_to 'New Campaign', new_campaign_path %>

app/views/campaigns/new.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'shared/campaign_navigation' %>
  </div>
  <div class="col-md-6">
    <%= render 'form', campaign: @campaign %>
  </div>
</div>

app/views/campaigns/preview.html.erb
<% @campaign.contacts.each do |contact| %>
  <p><strong>Email:</strong> <%= contact.email %></p>
  <p><strong>Subject line:</strong> <%= @campaign.name %></p>
  <p><strong>Email Body</strong>: <%= @campaign.render(contact) %></p>
<% end %>


<p>Do these emails look good? If so, then:</p>

<%= form_tag({action: :send_templated_email}) do %>
  <%= submit_tag "Send" %>
<% end %>

<p> Otherwise, <%= link_to "edit your campaign", edit_campaign_path(@campaign) %></p>

app/views/campaigns/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <strong>Name:</strong>
  <%= @campaign.name %>
</h1>

<%= link_to 'Edit', edit_campaign_path(@campaign) %> |
<%= link_to 'Back', campaigns_path %>